### ISSUE TITLE
TeX for the Impatient 的印刷版有没有人见过呢？

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-doc#3]
Original [issue 3](https://code.google.com/p/ctex-doc/issues/detail?id=3) created by zohooo@yeah.net on 2014-06-10T09:28:29.000Z:

TeX for the Impatient 的源码中包含了封面和各章的插图，
要是能把它们加到文档中来还是不错的。
不知道有没有人见过这本书的印刷版，在里面各章插图是怎么放置的呢？

**Comment by zohooo** [comment]
下面是 Karl Berry 之前的描述：
````
Each chapter's picture (ch*.png) appears on a left-hand page, opposite
the chapter opening on the right-hand page. 

watchrock.png appears on the title page, below "Illustrated by ..."
and also on pages that would otherwise be blank.
````
因此这个 issue 可以关闭了。
