### ISSUE TITLE
计划修改提交历史

### ISSUE THREAD

**Issue by zohooo** [CTeX-org/ctex-doc#4]
之前用 msysgit 没注意到默认会自动转换行尾符这回事，结果前面 impatient 翻译的提交彻底混乱了，一会是 windows 行尾符，一会又是 unix 行尾符，好几个提交结果变成整个文件都改变了。既然现在搬到 github 了，计划用 filter-branch 整理下提交历史，把这个问题解决。

顺便还有其他问题也计划一并处理：

1. 提交者的邮箱好多不对：比如变成 `zpxing@215b078e-49a1-11de-898f-4722afa3338a` 这种。
2. 很多提交信息前面没有说明对那个文档的修改，需要修改这些信息加注明。
3. 之前好多提交都同时更新 pdf 文档，这导致项目仓库太大。我觉得 pdf 只要放在 releases 中就可以了，计划在提交历史中删除 pdf 文档。

各位专家不知有何意见？

**Comment by LiamHuang0205** [comment]
提交者邮箱不对大概没什么办法，应该是 Leo 导入的时候没做这方面的处理，现在估计无法修复了。

提交信息说明不完整，这个能改当然要改。不过工程量估计有点大。

PDF 文档支持删除。放在 releases 里是个好办法。

换行符的话，按照原来 ctex-kit 的约定是统一到 Unix 上，这边也可以做一个约定。

**Comment by zohooo** [comment]
修改邮箱和修改别的内容是一样的方式，我以前修改过，应该不会太难。问题是现在 ctex-doc 的 google code 页面无法访问了，看不到他们的正确邮箱。

另外，既然 ctex-doc 保持单个项目的形式，为更好维护也方便用户抓取单个文档，我觉得可以干脆将每个文档作为一个分支，然后在 master 分支中用 submodule 包含它们进来。

**Comment by leo-liu** [comment]
Google code 上的用户名，如果没有特殊设置的话，就是 GMail 邮箱。

比如 nobody 就是 `nobody@gmail.com`，yuleopen 就是 `yuleopen@gmail.com`，zpxing 就是 `zpxing@gmail.com`。

剩下的人
* Chris.corsair 是 https://github.com/Corsair
* gzjjgod 是 https://github.com/jjgod
* leoliu.pku 是 https://github.com/leo-liu
* LiYanrui.m2 是 https://github.com/liyanrui
* luoyi.ly 是 https://github.com/luoyi
* zohooo@yeah.net 是你自己。

**Comment by zohooo** [comment]
另外，查看提交历史发现还有类似 luoyi@users.noreply.github.com 和 leo-liu@users.noreply.github.com 这样的邮箱（ctex-kit 和 ctex-doc 均如此），搜索了下发现是为了隐私保护，估计是转移时 Google 或是 Github 特地设定的。那这种形式的邮箱应该就不用去改动它们了吧？

**Comment by leo-liu** [comment]
github 的不用动，这个是转移的时候我设置绑定到 GitHub 帐号的。你也可以直接绑到帐号。

**Comment by zohooo** [comment]
还发现 asy-faq-zh-cn 和 asymptote-faq-zh-cn 目录的内容是一样的，从历史记录看来是忘记删除旧目录了。

**Comment by zohooo** [comment]
基本完成了，submodule 似乎太过复杂，所以没有用它。

git 的 filter-branch 命令功能强大也很复杂，这里总结一下以备以后参考。

修改提交者邮箱：
````bash
git filter-branch --env-filter '
  am="$GIT_AUTHOR_EMAIL"
  cm="$GIT_COMMITTER_EMAIL"
  if [ "$GIT_COMMITTER_EMAIL" = "yuleopen@215b078e-49a1-11de-898f-4722afa3338a" ]
  then
      am="yuleopen@example.com"
      cm="yuleopen@example.com"
  elif [ "$GIT_COMMITTER_EMAIL" = "zpxing@215b078e-49a1-11de-898f-4722afa3338a" ]
  then
      am="zpxing@example.com"
      cm="zpxing@example.com"
  fi
  export GIT_AUTHOR_EMAIL="$am"
  export GIT_COMMITTER_EMAIL="$cm"
'
````
将子目录独立作为新的分支：
````bash
git branch ctex-faq
git filter-branch -f --subdirectory-filter ctex-faq -- ctex-faq
````
删除提交历史中的文件：
````bash
git filter-branch -f --tree-filter 'test -f ctex-faq.pdf && rm ctex-faq.pdf || echo "Nothing to do"' ctex-faq
````
删除历史中的所有空白提交：
````bash
git filter-branch -f --prune-empty ctex-faq
````
将两段提交历史连接起来：
````bash
git filter-branch --parent-filter 'sed "s/^\$/-p f9b62a/"' HEAD
````
