### ISSUE TITLE
关于项目的组织方式

### ISSUE THREAD

**Issue by ghost** [CTeX-org/ctex-doc#5]
现在这样一个文档一个分支的方式，太奇异了。

* clone 下来之后，要查看文档，还得 `git checkout origin/<name-of-document>`
* 新建的文档，push 之后，项目首页不断提示「Compare & Pull Request」，各种烦= =……
* GitHub 的各种统计、数据分析，都向 master 分支看齐。

我觉着要不然还是像以前那样，一个目录一个文档。要不然就是把 ctex-doc 项目整个拆开，一个文档一个项目。

个人还是倾向于前者。

> natbib 暂时是打算拆到我个人 Repo 里去，最后搞完了再 pull request 回来。

**Comment by LiamHuang0205** [comment]
还有，branch name 和 tag name 重复了。push 都没法……

这太蛋疼了……

**Comment by zohooo** [comment]
tag name 改一下倒是不难。实际上我更倾向于一个文档一个项目，但 LeoLiu 似乎更喜欢放在一起。

放在一起，每个提交信息就得加上文档名，要不根本不知道是哪个文档的更新，而这挺繁琐的，而且很容易忘记。

放在分支这里，好处是容易和其它仓库同步，我就把原来放在 bitbucket 的 impatient 的提交历史同步过来了，想着稍后把 TeX by Topic 的翻译也同步过来，以后就直接在这里更新好了。

**Comment by zohooo** [comment]
要不我把其它文档都合并回主分支，仅留下 impatient 在旁支中。这样如何？

**Comment by leo-liu** [comment]
各有利弊吧。文档库其实问题不大，我的意思主要是 ctex-kit 那样的代码库应该放一起。代码项目之间往往是有相互依赖的，像 `ctex` 依赖 `zhnumber`、`zhmetrics` 和 `xeCJK` 等，放一个库里面工作方便一些，也使 l3build 这种更自动化的工具成为可能。

**Comment by zohooo** [comment]
Done，按照上述方式重新弄好了。

**Comment by leo-liu** [comment]
辛苦辛苦，我是觉得无所谓啦。倒是过滤处理邮箱是个功绩。

**Comment by zohooo** [comment]
从 @louisstuart96 最近更新的 lshort 情形来看，我觉得大型文档还是独立出来作一个项目更方便维护。
但我没有权限创建项目，@leo-liu @qinglee 能否分别给 impatient，textopic 和 lshort 创建三个项目，并把我们提交权限给我们呢？

**Comment by qinglee** [comment]
@zohooo 给了你 Owner 权限了，文档项目怎么组织就由你决定吧。

**Comment by zohooo** [comment]
把三个大型文档独立出来作为项目了。 @louisstuart96 这三个文档项目都你应该都有提交权限了。
